name: config_1

relations_2_obj:
    below:
        code: 0
        placement: below
    top:
        code: 1
        placement: top
    right:
        code: 2
        placement: right
    left:
        code: 3
        placement: left
    contact_below:
        code: 4
        placement: cbelow
    contact_on:
        code: 5
        placement: con
    contact_right:
        code: 6
        placement: cright
    contact_left:
        code: 7
        placement: cleft
    right_and_top:
        code: 8
        placement: right_and_top

   
relations_3_obj:
    aligned:
        code: 100
        switch: 0
        placement1: random
        placement2: aligned
    A_right_B_B_left_C:
        code: 101
        switch: 1
        placement1: left
        placement2: right
    A_right_B_A_top_C:
        code: 102
        switch: 0
        placement1: left
        placement2: below
    
params:
    n: 64
    noise: 0
    type: dsprites
    folder: custom
    file: test_4
    frame_size: 64
    patch_size: 16
    overlap: 1
      
